### ISSUE TITLE
Rust guidelines breaking examples

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/near-plugins#13]
There is an issue with the following lines of code as it breaks Rust code guidelines.

Should be `owner` ([REF](https://rust-lang.github.io/api-guidelines/naming.html?highlight=getter#getter-names-follow-rust-convention-c-getter)):
https://github.com/aurora-is-near/near-plugins/blob/9d17246b0ae7c4446b46b5b75fb4d55bfe6e9392/near-plugins/src/ownable.rs#L25

Should be `set_owner`:
https://github.com/aurora-is-near/near-plugins/blob/9d17246b0ae7c4446b46b5b75fb4d55bfe6e9392/near-plugins/src/ownable.rs#L34

Should be `is_owner`:
https://github.com/aurora-is-near/near-plugins/blob/9d17246b0ae7c4446b46b5b75fb4d55bfe6e9392/near-plugins/src/ownable.rs#L37

**Comment by mfornet** [comment]
The main idea of the prefix `owner_*` is to avoid conflicts with the potential implementation of functions with the same name. Similar to how NEP-141 does with public methods, adding the prefix `ft_*`. We could update this prefix to something different, but having them under the same prefix since like a sensible approach to me.

**Comment by joshuajbouw** [comment]
Ok, I agree with the context that it is a namespace for the methods to follow near conventions here. I do not like that too much, though, and I certainly wouldn't use that convention in typical Rust programming. I can not argue with what has already been defined.
