### ISSUE TITLE
ACL plugin: fix roles inclusion for admin user

### ISSUE THREAD

**Issue by sept-en** [aurora-is-near/near-plugins#32]
Currently, the admin of the specific role is actually not a member of this role. Therefore, the admin is not able to access the specific methods available for the given role.

**Comment by mooori** [comment]
That's actually intended behavior :) See the last two bullet points in [this comment](https://github.com/aurora-is-near/near-plugins/pull/5#discussion_r973784721).

Seems like OpenZeppelin behaves in the same way since they only consider `members` in `hasRole`:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3dac7bbed7b4c0dbf504180c33e8ed8e350b93eb/contracts/access/AccessControl.sol#L81-L86

**Comment by mfornet** [comment]
As mentioned, this is the intended behavior, not a bug.
